version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_in9_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passw0rdIn9
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - in-nine
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    networks:
      - in-nine
    environment:
      PGADMIN_DEFAULT_EMAIL: postgresql@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  mailpit:
    image: axllent/mailpit
    container_name: client-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - in-nine
    volumes:
      - mailpit-data:/data

volumes:
  local_pgdata:
  pgadmin-data:
  mailpit-data:

networks:
  in-nine:
